# Generated by Django 5.1.15 on 2026-09-28 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('seccion', models.CharField(choices=[('novedades', 'Novedades'), ('nosotras', 'Nosotras'), ('recursos', 'Recursos')], default='novedades', max_length=20)),
                ('resumen', models.CharField(blank=True, help_text='Bajada corta para el listado. Opcional.', max_length=280)),
                ('cuerpo', models.TextField(help_text='Texto de la entrada. Se guarda sin etiquetas HTML (sanitizado).')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cms/%Y/%m/')),
                ('meta_titulo', models.CharField(blank=True, max_length=70, verbose_name='meta título (SEO)')),
                ('meta_descripcion', models.CharField(blank=True, max_length=160, verbose_name='meta descripción (SEO)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos_cms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contenido del sitio',
                'verbose_name_plural': 'contenidos del sitio',
                'db_table': 'sitio_contenidos',
                'ordering': ['orden', '-publicado_en', '-creado_en'],
            },
        ),
    ]
