# Generated by Django 5.1.15 on 2026-09-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_table'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece. Solo aplica a Cliente aprobador / Cliente lector.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='clients.cliente', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='user',
            name='clientes_asignados',
            field=models.ManyToManyField(blank=True, help_text='Clientes que puede ver. Solo aplica al rol Colaboradora.', related_name='colaboradoras', to='clients.cliente', verbose_name='clientes asignados'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('administradora', 'Administradora'), ('colaboradora', 'Colaboradora'), ('cliente_aprobador', 'Cliente aprobador'), ('cliente_lector', 'Cliente lector')], help_text='Rol dentro de la plataforma (Alcance 4.3). Vacío = sin rol asignado todavía.', max_length=20, verbose_name='rol'),
        ),
    ]
