# Generated by Django 5.1.15 on 2026-09-24 23:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_catalogo_inicial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], db_index=True, default='borrador', max_length=10)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('valida_hasta', models.DateField(blank=True, null=True, verbose_name='válida hasta')),
                ('forma_pago', models.CharField(choices=[('transferencia_mensual', 'Transferencia mensual'), ('semestral', 'Pago semestral anticipado'), ('tarjeta', 'Tarjeta de crédito (recurrente)')], default='transferencia_mensual', max_length=30, verbose_name='forma de pago')),
                ('descuento_pct', models.PositiveSmallIntegerField(default=0, verbose_name='descuento (%)')),
                ('inicio_estimado', models.DateField(blank=True, null=True, verbose_name='inicio estimado')),
                ('diagnostico', models.TextField(blank=True, verbose_name='diagnóstico')),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=160, verbose_name='descripción')),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('valor_unitario', models.PositiveIntegerField(verbose_name='valor unitario (CLP)')),
                ('meses', models.PositiveSmallIntegerField(blank=True, help_text='Vacío = cobro único.', null=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.cotizacion')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.plan')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.servicio')),
            ],
            options={
                'verbose_name': 'ítem de cotización',
                'verbose_name_plural': 'ítems de cotización',
                'db_table': 'cotizacion_items',
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('empresa', models.CharField(max_length=160)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('rubro', models.CharField(choices=[('Gastronomía y cafeterías', 'Gastronomía y cafeterías'), ('Retail y moda', 'Retail y moda'), ('Salud y bienestar', 'Salud y bienestar'), ('Belleza y estética', 'Belleza y estética'), ('Servicios profesionales', 'Servicios profesionales'), ('Educación', 'Educación'), ('Inmobiliaria y construcción', 'Inmobiliaria y construcción'), ('Turismo y hotelería', 'Turismo y hotelería'), ('Marca personal', 'Marca personal'), ('Otro', 'Otro')], max_length=60)),
                ('region', models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaíso', 'Valparaíso'), ('Metropolitana de Santiago', 'Metropolitana de Santiago'), ("O'Higgins", "O'Higgins"), ('Maule', 'Maule'), ('Ñuble', 'Ñuble'), ('Biobío', 'Biobío'), ('La Araucanía', 'La Araucanía'), ('Los Ríos', 'Los Ríos'), ('Los Lagos', 'Los Lagos'), ('Aysén', 'Aysén'), ('Magallanes', 'Magallanes')], max_length=60, verbose_name='región')),
                ('tamano', models.CharField(choices=[('solo', 'Solo yo / emprendimiento'), ('2_10', '2 a 10 personas'), ('11_50', '11 a 50 personas'), ('51_mas', 'Más de 50 personas')], max_length=10, verbose_name='tamaño')),
                ('agencia_actual', models.CharField(choices=[('no', 'No'), ('si', 'Sí'), ('freelance', 'Freelance')], max_length=10, verbose_name='¿trabaja con agencia?')),
                ('presupuesto', models.CharField(choices=[('menos_150', 'Menos de $150.000'), ('150_250', '$150.000 – $250.000'), ('250_350', '$250.000 – $350.000'), ('mas_350', 'Más de $350.000')], max_length=10, verbose_name='presupuesto mensual')),
                ('objetivos', models.JSONField(blank=True, default=list)),
                ('redes_actuales', models.JSONField(blank=True, default=list)),
                ('instagram', models.CharField(blank=True, max_length=60, verbose_name='usuario de Instagram')),
                ('instagram_seguidores', models.PositiveIntegerField(blank=True, help_text='Lo completa el equipo al revisar la cuenta.', null=True, verbose_name='seguidores en Instagram')),
                ('sitio_web', models.URLField(blank=True, verbose_name='sitio web')),
                ('situacion_actual', models.TextField(blank=True, verbose_name='situación actual')),
                ('como_nos_conocio', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('recomendacion', 'Recomendación'), ('google', 'Google'), ('linkedin', 'LinkedIn'), ('otro', 'Otro')], max_length=20, verbose_name='¿cómo nos conoció?')),
                ('canal', models.CharField(choices=[('formulario_sitio', 'Formulario del sitio'), ('manual', 'Ingreso manual')], default='formulario_sitio', max_length=20)),
                ('etapa', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('reunion', 'Reunión'), ('cotizacion_enviada', 'Cotización enviada'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], db_index=True, default='nuevo', max_length=20)),
                ('acepta_privacidad', models.BooleanField(default=False, verbose_name='acepta la política de privacidad')),
                ('diagnostico_ia', models.TextField(blank=True, verbose_name='diagnóstico (borrador IA)')),
                ('diagnostico_generado_en', models.DateTimeField(blank=True, null=True)),
                ('diagnostico_revisado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(blank=True, help_text='Se completa al convertir el prospecto en cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospecto', to='clients.cliente')),
                ('diagnostico_revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.plan', verbose_name='plan de interés')),
                ('plan_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.plan', verbose_name='plan sugerido')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('servicios_requeridos', models.ManyToManyField(blank=True, related_name='prospectos', to='catalog.servicio')),
            ],
            options={
                'verbose_name': 'prospecto',
                'verbose_name_plural': 'prospectos',
                'db_table': 'prospectos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('correo', 'Correo'), ('llamada', 'Llamada'), ('reunion', 'Reunión'), ('nota', 'Nota interna'), ('sistema', 'Sistema')], max_length=10)),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='crm.prospecto')),
            ],
            options={
                'verbose_name': 'interacción',
                'verbose_name_plural': 'interacciones',
                'db_table': 'interacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='prospecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='crm.prospecto'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('completada', models.BooleanField(default=False)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prospecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='crm.prospecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'db_table': 'tareas',
                'ordering': ['completada', 'fecha', 'creado_en'],
            },
        ),
    ]
