# Generated by Django 5.1.15 on 2026-10-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='rut',
            field=models.CharField(blank=True, help_text='Formato 12.345.678-5. Se pide solo en el registro manual.', max_length=12, verbose_name='RUT'),
        ),
    ]
