# Generated by Django 5.1.15 on 2026-09-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diagnostico_cotizacion', 'Diagnóstico de cotización'), ('reporte_mensual', 'Reporte mensual'), ('copy', 'Copy con voz de marca')], max_length=30)),
                ('proveedor', models.CharField(default='gemini', max_length=30)),
                ('modelo', models.CharField(max_length=60)),
                ('tokens_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'registro de IA',
                'verbose_name_plural': 'registros de IA',
                'db_table': 'registros_ia',
                'ordering': ['-creado_en'],
            },
        ),
    ]
