# Generated by Django 5.1.15 on 2026-09-25 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar')], max_length=10, verbose_name='acción')),
                ('entidad', models.CharField(help_text="Qué se modificó, ej. 'usuario'", max_length=100, verbose_name='entidad')),
                ('entidad_id', models.CharField(blank=True, max_length=50, verbose_name='ID de la entidad')),
                ('detalle', models.CharField(blank=True, max_length=255, verbose_name='detalle')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('usuario', models.ForeignKey(help_text='Quién ejecutó la acción. Vacío si la cuenta fue eliminada después.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'db_table': 'registro_auditoria',
                'ordering': ['-creado_en'],
            },
        ),
    ]
