# Generated by Django 5.1.15 on 2026-09-24 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio_mensual', models.PositiveIntegerField(verbose_name='precio mensual (CLP)')),
                ('precio_primer_mes', models.PositiveIntegerField(blank=True, help_text='Solo si el primer mes cuesta distinto (p. ej. Expansión). Vacío = igual al mensual.', null=True, verbose_name='precio del primer mes (CLP)')),
                ('destacado', models.BooleanField(default=False, verbose_name='destacado en el sitio')),
                ('etiqueta', models.CharField(blank=True, help_text='Ej.: MÁS CONTRATADO. Se muestra sobre la tarjeta.', max_length=40)),
                ('visible_en_sitio', models.BooleanField(default=True, verbose_name='visible en el sitio')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar en vez de borrar: los contratos existentes lo siguen usando.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'planes',
                'db_table': 'planes',
                'ordering': ['orden', 'precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio', models.PositiveIntegerField(verbose_name='precio (CLP)')),
                ('modalidad_cobro', models.CharField(choices=[('hora', 'Por hora'), ('unico', 'Pago único'), ('campana', 'Por campaña'), ('paquete', 'Por paquete'), ('mensual', 'Mensual')], max_length=10, verbose_name='modalidad de cobro')),
                ('visible_en_sitio', models.BooleanField(default=True, verbose_name='visible en el sitio')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'db_table': 'servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEntregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('nombre_plural', models.CharField(blank=True, help_text='Ej.: historias. Se usa en «16 historias».', max_length=80, verbose_name='nombre en plural')),
                ('slug', models.SlugField(unique=True)),
                ('tiene_cuota', models.BooleanField(default=False, help_text='Marcado: se entrega una cantidad al mes y cuenta para el cumplimiento del plan (historias, carruseles, reels).', verbose_name='tiene cuota mensual')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de entregable',
                'verbose_name_plural': 'tipos de entregable',
                'db_table': 'tipos_entregable',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanEntregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_mensual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='catalog.plan')),
                ('tipo_entregable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.tipoentregable', verbose_name='entregable')),
            ],
            options={
                'verbose_name': 'entregable del plan',
                'verbose_name_plural': 'entregables del plan',
                'db_table': 'planes_entregables',
                'ordering': ['tipo_entregable__orden'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='tipos_entregable',
            field=models.ManyToManyField(related_name='planes', through='catalog.PlanEntregable', to='catalog.tipoentregable'),
        ),
        migrations.AddConstraint(
            model_name='planentregable',
            constraint=models.UniqueConstraint(fields=('plan', 'tipo_entregable'), name='plan_entregable_unico'),
        ),
    ]
