# Generated by Django 5.1.15 on 2026-10-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogo_inicial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo del contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=120, verbose_name='contacto principal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='teléfono del contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='directrices_marca',
            field=models.TextField(blank=True, help_text='Tono, público objetivo, lineamientos y restricciones.', verbose_name='directrices de marca'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='inicio del contrato'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otra', 'Otra')], max_length=15, verbose_name='forma de pago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='objetivos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='catalog.plan', verbose_name='plan contratado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='region',
            field=models.CharField(blank=True, choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaíso', 'Valparaíso'), ('Metropolitana de Santiago', 'Metropolitana de Santiago'), ("O'Higgins", "O'Higgins"), ('Maule', 'Maule'), ('Ñuble', 'Ñuble'), ('Biobío', 'Biobío'), ('La Araucanía', 'La Araucanía'), ('Los Ríos', 'Los Ríos'), ('Los Lagos', 'Los Lagos'), ('Aysén', 'Aysén'), ('Magallanes', 'Magallanes')], max_length=60, verbose_name='región'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rubro',
            field=models.CharField(blank=True, choices=[('Gastronomía y cafeterías', 'Gastronomía y cafeterías'), ('Retail y moda', 'Retail y moda'), ('Salud y bienestar', 'Salud y bienestar'), ('Belleza y estética', 'Belleza y estética'), ('Servicios profesionales', 'Servicios profesionales'), ('Educación', 'Educación'), ('Inmobiliaria y construcción', 'Inmobiliaria y construcción'), ('Turismo y hotelería', 'Turismo y hotelería'), ('Marca personal', 'Marca personal'), ('Otro', 'Otro')], max_length=60),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, help_text='Formato 12.345.678-5. Vacío si aún no lo tiene (p. ej. empresa extranjera).', max_length=12, verbose_name='RUT'),
        ),
    ]
