# Generated by Django 5.1.15 on 2026-10-05 15:50

import apps.clients.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_cliente_ficha_comercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('directrices', 'Directrices de marca'), ('propuesta', 'Propuesta o cotización'), ('otro', 'Otro')], default='otro', max_length=15)),
                ('archivo', models.FileField(upload_to=apps.clients.models.ruta_documento)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clients.cliente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'documento del cliente',
                'verbose_name_plural': 'documentos del cliente',
                'db_table': 'clientes_documentos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
