# Generated by Django 5.1.15 on 2026-10-05 16:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_documento_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPICliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('indicador', models.CharField(choices=[('seguidores', 'Seguidores'), ('alcance', 'Alcance'), ('interacciones', 'Interacciones'), ('visitas', 'Visitas'), ('clics', 'Clics')], max_length=20)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor inicial')),
                ('meta', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clients.cliente')),
            ],
            options={
                'verbose_name': 'KPI del cliente',
                'verbose_name_plural': 'KPIs del cliente',
                'db_table': 'clientes_kpis',
                'ordering': ['indicador'],
            },
        ),
        migrations.CreateModel(
            name='MedicionKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('fuente', models.CharField(choices=[('manual', 'Manual'), ('importada', 'Importada')], default='manual', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='clients.cliente')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='clients.kpicliente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'medición de KPI',
                'verbose_name_plural': 'mediciones de KPI',
                'db_table': 'clientes_kpis_mediciones',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='kpicliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'indicador'), name='kpi_unico_por_cliente_e_indicador'),
        ),
        migrations.AddConstraint(
            model_name='kpicliente',
            constraint=models.CheckConstraint(condition=models.Q(('meta__gt', models.F('valor_inicial'))), name='kpi_meta_mayor_que_inicial'),
        ),
    ]
